services:
    ddns-gost-realm:
      image: ddns-gost-realm:latest
      container_name: ddns-gost-realm
      restart: always
      ports:
        - 9876:9876
        - 8890:8890
      volumes:
        - ./data:/root
      network_mode: bridge
